version: "3.7"
services:
  postgres:
    container_name: collector_postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collector_dev
    ports:
      - 5432:5432